# Site
repository: manpreet-singh/manpreet-singh.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Manpreet Singh
title: Electrical/Hardware Engineer
email: singh-manpreet@outlook.com
website: manpreet-singh.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  manpreet-singh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: manpreet-singh-b35203149
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Manpreet and I'm a Electrical Engineer. As well as developing custom hardware solutions I also have experience making software. I am currently in Grad School part time while working as a Full Time Engineer.

  I am most skilled in: <mark>Embedded Hardware</mark>, <mark>C/C++</mark>, <mark>Computer Vision</mark>, and <mark>Low Level Software</mark>.


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        sub_title: Hardware Test Engineer II
        caption: July 2021 - January 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          At this role I performed Design Validation on the Surface line of computer products. Some of my achievements and responsibilities 
            - Develop internal tools for data collection, ingest, and analysis automation using C# and Python.
            - Develop and maintain test equipment and test stands consisting of multiple Oscilloscopes, DMMs, Function Generators, and Current Probes for mixed Analog and Digital testing and Verification.
            - Developed test automation software with C# and Python using VISA and SCPI to interface with various test instruments.
            - Carry out display verification by taking ownership of test pass planning and execution for various display subsystems across a product line from an electrical and optical point of view. Review PCB layouts using Cadence Allegro PCB viewer, develop PCB rework guides for electrical testing.
            - Verification of MIPI, I2C, SPI, DP, eDP, Signal Integrity, complex power sequences, display driver ICs, and multi-display synchronization.
            - Thoroughly document issues from electrical and optical points of view

      - layout: left
        title: Zeva Aero
        sub_title: Electrical Engineering Intern
        caption: Jan. 2021 - Jun. 2021
        description: | # this will include new lines to allow paragraphs
          At this role I helped prototype and assemble Power Electronics for a prototype electric aircraft along with the following responsibilities:
            - Participated in test coordination meetings, on-aircraft ground testing and instrumentation installations.
            - Collected, analyzed, and interpreted data from various test stands with the goal of performing product performance analysis. 
            - Developed C/C++ Firmware for the STM 32-bit Microcontroller to interface with sensors via I2C and CAN for the purposes of logging data for analysis.
            - Researched and Designed Mixed analog/digital Circuits and PCBs under supervision of senior engineers.
            - Verified electrical assemblies using lab test equipment such as function generators and Oscilloscopes.
            - Designed 3D printed enclosures for sensor systems and electronic hardware using Solidworks 3D CAD. 
            - Collaborated with other Interns to develop a user interface that displayed collected data from the various sensors across the aircraft utilizing Python and 3rd party libraries all running aboard a Raspberry Pi



  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Custom Micro-controller Board
        link: manpreet-singh.github.io/Atlas/
        # link_text: Project Website
        additional_links:
          - title:  manpreet-singh/Atlas
            icon: fab fa-github
            url: github.com/manpreet-singh/Atlas
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Small Robot meant to drive around a room autonomously
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>Embedded Systems</mark> design and it has since grown into a fully fledged robot. I have learned many skills through this and been I'm very proud of having this in my portfolio.

          Some of the skills I've picked up while doing this project:
          - C/C++
          - Embedded hardware design with STM32 micro-controllers
          - Digital Signal processing with Inertial Measurement Units (IMUs)
          - PCB Design and Assembly
          - Power Management topology with Lithium-Ion Batteries

      - layout: left
        title: Networked Multi-Agent Robotics
        link: github.com/CAMP-Project/CAMP
        additional_links:
          - title: CAMP-Project/CAMP
            icon: fab fa-github
            url: github.com/CAMP-Project/CAMP
        quote: >
          Coordinated Autonomous Mapping & Pathfinding
        description: | 
          This project was my Undergraduate capstone research project involving distributed Robotics and various fun technologies.

          Main goal was to develop a network of 3 independent robots that had the ability to collaborate with one another given they were within Wi-Fi range of each other to map out a space or room using LIDAR.

          Some of the complexities in this project involved figuring out techniques to merge LIDAR information from multiple sources into a single map of sorts. Our approach involved transformations, signal filtering, and localization techniques for the mobiles robots.

          We used 2D transformations to get the LIDAR information into a shared point of reference in the real world. We also used a Extended Kalman Filter to get a better estimate of the robot's precise location using the wheel odometery data and a time of flight localization sensor. 



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Washington (Seattle)
        caption: 2022 - 2024 (estimated)
        sub_title: MSc Electrical Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I will be starting my Masters Program in EE at UW Seattle Fall of 2022. Current Plan is to focus on Artificial intelligence and Computer Vision with this degree.

      - layout: left
        title: University of Washington (Tacoma)
        caption: Sept. 2019 - June 2021
        sub_title: BSc Electrical Engineering (3.84 GPA)

        description: |
          During my time at UW Tacoma, I honed and refined my skills that I can taken through my career such as teamwork and working with tight deadlines. I enjoyed my time at UW Tacoma and learnt a lot about what a healthy work life balance is. 
          
          Some of the skills I picked up while here include : 
          - 3D Printing
          - Mechanical Design
          - Software Design for Embedded Systems
          - Image processing 
          - Control System
          - Digital Signal Processing

          I spent some time with the IEEE Robotics Club at UW Tacoma, initially during the first year I helped wherever I was needed. I was a jack of *most* trades taking on the role of *Project Manager*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Running
      - Gaming
      - Cooking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
