# Site
repository: manpreet-singh/manpreet-singh.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Manpreet Singh
title: Electrical/Hardware Engineer
email: singh-manpreet@outlook.com
website: manpreet-singh.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  manpreet-singh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: manpreet-singh-b35203149
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Manpreet and I'm a Electrical Engineer. As well as developing custom hardware solutions I also have experience making software. I am currently a Grad Student at the University of Washington working towards a MSc. in Electrical Engineering.

  I am most skilled in: <mark>Embedded Hardware</mark>, Embedded <mark>Software Development</mark>, <mark>System Design</mark>, <mark>Hardware Testing</mark>, and <mark>Low Level Software</mark> (Firmware for Microcontrollers and FPGAs).


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Blue Origin
        sub_title: Graduate Avionics Intern
        caption: Jan. 2023 - Apr. 2023
        description: |
          During my time at Blue Origin, I worked on Test Infrastructure for use in their Hardware in the Loop labs. The Testing infrastructure I helped develop is meant to help perform Qualification and Acceptance Testing.
          Some of my responsibilities include
            - Developed <mark>LabVIEW</mark> code to run on a NI PXI Chassis to simulate analog instrumentation commonly found on the BE-3PM Engine.
            - Developed a data post-processing pipeline in <mark>Python</mark> to analyze voltage accuracy.
            - Authored Block Interface Diagrams for Test Hardware and Harness design/build documents.
            - Developed Test hardware to catch timeouts on a <mark>RS488</mark> communication bus. A <mark>Python</mark> script ran on a <mark>Linux</mark> Server monitoring for timeouts, when a timeout was detected, a Saleae Logic Analyzer was triggered to save the last minute of data it had captured.

      - layout: left
        title: Microsoft
        sub_title: Hardware Test Engineer II
        caption: Jul. 2021 - Jan. 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          At this role I performed Design Validation on the Surface line of computer products. Some of my achievements and responsibilities 
            - Develop internal tools for data collection, ingest, and analysis automation using <mark>Python</mark>.
            - Develop and maintain test equipment and test stands consisting of multiple Oscilloscopes, DMMs, Function Generators, and Current Probes for mixed Analog and Digital testing and Verification.
            - Developed test automation software with <mark>C#</mark> using VISA and SCPI to interface with test instruments.
            - Took ownership of test pass planning and execution for various display subsystems across a product line from an electrical and optical point of view. 
            - Review PCB layouts using Cadence Allegro PCB viewer, develop PCB rework guides for electrical testing.
            - Verification of MIPI, <mark>I2C</mark>, <mark>SPI</mark>, DP, eDP, Signal Integrity, complex power sequences, display driver ICs, and multi-display synchronization.

      - layout: left
        title: Zeva Aero
        sub_title: Electrical Engineering Intern
        caption: Jan. 2021 - Jun. 2021
        description: | # this will include new lines to allow paragraphs
          At this role I helped prototype and assemble Power Electronics for a prototype electric aircraft along with the following responsibilities:
            - Participated in test coordination meetings, on-aircraft ground testing and instrumentation installations.
            - Collected, analyzed, and interpreted data from various test stands with the goal of performing product performance analysis. 
            - Developed C/C++ Firmware for the STM 32-bit Microcontroller to interface with sensors via <mark>I2C</mark> for the purposes of logging data for analysis.
            - Researched and Designed Mixed analog/digital Circuits and PCBs under supervision of senior engineers.
            - Verified electrical assemblies using lab test equipment such as function generators and Oscilloscopes.
            - Designed 3D printed enclosures for sensor systems and electronic hardware using Solidworks 3D CAD. 
            - Collaborated with other Interns to develop a user interface that displayed collected data from the various sensors across the aircraft utilizing Python and 3rd party libraries all running aboard a Raspberry Pi



  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Custom Flight/Robot Controller
        link: manpreet-singh.github.io/Atlas/
        # link_text: Project Website
        additional_links:
          - title:  manpreet-singh/Atlas
            icon: fab fa-github
            url: github.com/manpreet-singh/Atlas
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Quadcopter Controller developed for educational purposes
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>Embedded Systems</mark> design and it has since grown into a fully fledged flight controller. I have learned many skills through this and been I'm very proud of having this in my portfolio.

          Some of the skills I've picked up while doing this project:
          - C/C++ , Python , Linux
          - Embedded hardware design with STM32 micro-controllers
          - Digital Signal processing with Inertial Measurement Units (IMUs)
          - PCB Design and Assembly with different CAD packages such as KiCAD & Altium Designer
          - Power Management topology with Lithium-Ion Batteries

      - layout: left
        title: Networked Multi-Agent Robotics
        link: github.com/CAMP-Project/CAMP
        additional_links:
          - title: CAMP-Project/CAMP
            icon: fab fa-github
            url: github.com/CAMP-Project/CAMP
        quote: >
          Coordinated Autonomous Mapping & Pathfinding
        description: | 
          This project was my Undergraduate capstone research project involving distributed <mark>Robotics</mark> and various fun technologies.

          Main goal was to develop a network of 3 independent robots that had the ability to collaborate with one another given they were within Wi-Fi range of each other to map out a space or room using <mark>LIDAR</mark> and <mark>SLAM</mark>.

          Some of the complexities in this project involved figuring out techniques to merge SLAM data from multiple sources into a single dataset. Our approach involved 2D rotations/translations, signal filtering, and localization techniques for the mobiles robots.

          We used 2D transformations to get the SLAM data into a shared point of reference in the real world. We also used a Extended Kalman Filter to get a better estimate of the robot's precise location using the wheel odometery data and a time of flight localization sensor. 

          Some of the things I had direct ownership of are the following:
          - Design & Development of the Movement Controller. This part of the software was in-charge of triangulating the position of the robot and figuring out what commands to send to the Robot hardware in order to move from it's current position to a defined set of coordinates.
          - Conceptualizing & Developing the Multi robot communication. This specific part of the software was in-charge of identifying and initiating communication with other networked robots. Other aspects of this specific feature was data encoding and decoding.
          - Development of the Hardware Test Plan. I created a pre-initialization routine that checked in with all of the required hardware to ensure proper functionality.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Washington (Seattle, WA)
        caption: Sept. 2022 - Dec. 2023
        sub_title: MSc. Electrical Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my Masters, I focused on a combination of the following topics I found interesting from my Bachelor's degree:
          - Digital Signal Processing
          - Control Systems
          - Analog Sensor Systems Design
          - Embedded System Design, with a focus on AI on low cost hardware
          - Digital Systems Design with FPGAs

          Some of the projects I worked on during my Masters were:
          - Design of an Instrumentation Amplifier and a 4th order low pass filter
          - Digital Signal Processing for Continuous Wave Radars. This project aimed to deal with RF signals that had multiple harmonics, aim was to identify the fundamental frequency from the higher order harmonics.
          - Field Oriented Control (FOC) of an Induction Motor, this project aimed to develop a Field Oriented Controller for an induction motor.
          - Closed Loop Current Controller for a BLDC motor built onto an FPGA. This project also included design of the measurement circuitry and development of a I2C interface on the FPGA to communicate with the measurement circuitry.

      - layout: left
        title: University of Washington (Tacoma, WA)
        caption: Sept. 2019 - Jun. 2021
        sub_title: BSc Electrical Engineering

        description: |
          During my time at UW Tacoma, I honed and refined my skills that I can taken through my career such as teamwork and working with tight deadlines. I enjoyed my time at UW Tacoma and learnt a lot about what a healthy work life balance is. 
          
          Some of the skills I picked up while here include : 
          - 3D Printing
          - Software Design for Embedded Systems
          - Image processing 
          - Control System
          - Digital Signal Processing

          I was also founding member of the IEEE Robotics Club and the IEEE Honor Society at UW Tacoma.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in hardware and software engineering some of my other interests and hobbies are:
      - Badminton
      - Gaming (Kerbal Space Program)
      - Cooking
      - 3D Printing
      - Fitness

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
